"""for personal user

Revision ID: 1c9bb7c02e0f
Revises: 2f2bc3d76032
Create Date: 2024-04-14 18:18:34.327426

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1c9bb7c02e0f"
down_revision: Union[str, None] = "2f2bc3d76032"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
