"""for personal user

Revision ID: 20461ef1b13f
Revises: 1c9bb7c02e0f
Create Date: 2024-04-14 18:19:28.500920

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "20461ef1b13f"
down_revision: Union[str, None] = "1c9bb7c02e0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
