"""for personal user

Revision ID: 24cc381c93fc
Revises: 42a9d6e796d6
Create Date: 2024-04-19 17:14:36.043899

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "24cc381c93fc"
down_revision: Union[str, None] = "42a9d6e796d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
