"""for personal user

Revision ID: 2f2bc3d76032
Revises: fb850b7bee74
Create Date: 2024-04-14 18:07:59.780198

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2f2bc3d76032"
down_revision: Union[str, None] = "fb850b7bee74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
