"""for personal user

Revision ID: 39ebea04b7c6
Revises: e5000b4891bd
Create Date: 2024-04-10 17:54:36.446994

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "39ebea04b7c6"
down_revision: Union[str, None] = "e5000b4891bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
