"""for personal user

Revision ID: 69d7f89aa72b
Revises: 24cc381c93fc
Create Date: 2024-04-19 17:18:49.130855

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "69d7f89aa72b"
down_revision: Union[str, None] = "24cc381c93fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
