"""for personal user

Revision ID: 7fcf68c01df5
Revises: 20461ef1b13f
Create Date: 2024-04-14 18:25:28.467298

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7fcf68c01df5"
down_revision: Union[str, None] = "20461ef1b13f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
