"""for personal user

Revision ID: 844b7090176b
Revises: a3834b2e54d5
Create Date: 2024-04-11 14:56:11.795898

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "844b7090176b"
down_revision: Union[str, None] = "a3834b2e54d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
