"""for personal user

Revision ID: a3834b2e54d5
Revises: e029d5553083
Create Date: 2024-04-11 11:29:29.224355

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a3834b2e54d5"
down_revision: Union[str, None] = "e029d5553083"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
