"""for accounts

Revision ID: c85f7866e472
Revises: dbf0ddd29a79
Create Date: 2024-04-22 20:35:01.410292

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c85f7866e472"
down_revision: Union[str, None] = "dbf0ddd29a79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expenses", sa.Column("account_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "expenses", "accounts", ["account_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "expenses", type_="foreignkey")
    op.drop_column("expenses", "account_id")
    # ### end Alembic commands ###
