"""for personal user

Revision ID: caec2b84b75f
Revises: 7fcf68c01df5
Create Date: 2024-04-17 17:23:31.965599

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "caec2b84b75f"
down_revision: Union[str, None] = "7fcf68c01df5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
