"""for personal user

Revision ID: e0cf7ba1e3f0
Revises: caec2b84b75f
Create Date: 2024-04-17 17:27:02.206374

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e0cf7ba1e3f0"
down_revision: Union[str, None] = "caec2b84b75f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
