"""for accounts

Revision ID: e1ff3e7ada0b
Revises: c85f7866e472
Create Date: 2024-04-22 20:44:51.499845

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1ff3e7ada0b"
down_revision: Union[str, None] = "c85f7866e472"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "description")
    # ### end Alembic commands ###
