"""add model

Revision ID: e46f6e14b2ed
Revises: aad6018c07b9
Create Date: 2024-04-08 08:50:38.353330

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e46f6e14b2ed"
down_revision: Union[str, None] = "aad6018c07b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
