"""for personal user

Revision ID: fb850b7bee74
Revises: 844b7090176b
Create Date: 2024-04-11 14:59:09.125588

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fb850b7bee74"
down_revision: Union[str, None] = "844b7090176b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
